### ISSUE TITLE
Presledki in link na igrico

### ISSUE THREAD

**Issue by andrejbauer** [LukaAvbreht/Nine-Mens-Morris#1]
`README.md` bi lahko bil malo bolj informativen in vseboval link na opis igrice.

Pa v načrtu popravita pravopis. Piše se "1. in 2. teden" in ne "1.,2.teden". Za piko je preslede in če se našteva dve stvari, potem je vmes besedica "in".

**Comment by andrejbauer** [comment]
Pa še `5.teden` je `5. teden` ;-)

**Comment by andrejbauer** [comment]
By the way, ko bosta zadovoljna s popravki, zaprita tale issue, da bom videl in lahko popravim oceno.

**Comment by LukaAvbreht** [comment]
Mislim da sva popravila use težave

**Comment by andrejbauer** [comment]
Zdaj pojdi pa prebrat https://ucilnica.fmf.uni-lj.si/mod/forum/discuss.php?d=6533 :-)
